MicroTube: App.cpp File Reference
App.cpp File Reference
#include "AppComponent.hpp"
#include "controller/StaticController.hpp"
#include "controller/VideoController.hpp"
#include "controller/UserController.hpp"
#include "controller/ChannelController.hpp"
#include "oatpp-swagger/AsyncController.hpp"
#include "oatpp/network/Server.hpp"
Functions
void run ()
int main (int, const char *)
Function Documentation
main()
int main (int , const char *)
Definition at line 61 of file App.cpp.
References run().
run()
void run ()
Definition at line 10 of file App.cpp.
References microTube::apicontroller::ChannelController::createShared(), microTube::apicontroller::StaticController::createShared(), and microTube::apicontroller::VideoController::createShared().