MicroTube: microTube::video::VideoIndexer Class Reference
microTube::video::VideoIndexer Class Reference
#include <VideoIndexer.hpp>
Public Types
enum UUIDSort { UUIDSortDate , UUIDSortLikes , UUIDSortDislikes , UUIDSortUniqueViews }
enum SortStyle { SortStyleASC , SortStyleDESC }
using InfoDTO = microTube::dto::InfoJsonDTO
using UUIDList = oatpp::List<oatpp::String>
using VideoInfo = oatpp::Object<InfoDTO>
using VideoInfoMap = std::unordered_map<std::string, VideoInfo>
using VideoInfoList = std::list<VideoInfo>
Public Member Functions
VideoIndexer (const std::string &BasePath)
~VideoIndexer ()
std::pair< VideoInfoMap, uintmax_t > getVideoMap ()
void sortBy (const UUIDSort sortCategory, UUIDList &list, const SortStyle sortStyle=SortStyleASC)
oatpp::UInt64 getLikeCountFor (const std::string &uuid)
oatpp::UInt64 getDisikeCountFor (const std::string &uuid)
oatpp::UInt64 getUniqueViewCountFor (const std::string &uuid)
UUIDList getFullList ()
UUIDList getChannelList (const oatpp::UInt64 channelId)
UUIDList getCategoryList (const oatpp::String &category)
VideoInfoList getInfosFor (const UUIDList &list)
VideoInfo lookupInfoManual (const std::string &uuid)
VideoInfo lookupInfo (const std::string &uuid)
bool updateVideoInfo (const oatpp::Object< InfoDTO > &dto, const bool isNew=false)
UUIDList searchFor (const std::string &str, const size_t amount=15)
Static Public Member Functions
static void IndexingThread (VideoIndexer *const instance)
static VideoInfo lookupInfoManual (const std::string &uuid, const std::string &VideoDirectory)
Private Member Functions
void SortDate (UUIDList &list, const SortStyle sortStyle)
void SortLikes (UUIDList &list, const SortStyle sortStyle)
void SortDislikes (UUIDList &list, const SortStyle sortStyle)
void SortUniqueViews (UUIDList &list, const SortStyle sortStyle)
OATPP_COMPONENT (std::shared_ptr< oatpp::data::mapping::ObjectMapper >, m_ObjectMapper)
OATPP_COMPONENT (std::shared_ptr< microTube::component::DatabaseClient >, m_database)
Private Attributes
std::string m_BasePath
std::thread m_worker
struct {
std::mutex mtx
VideoInfoMap videos
} m_videos
std::atomic< bool > m_end
std::condition_variable m_cv
Detailed Description
Definition at line 36 of file VideoIndexer.hpp.
Member Typedef Documentation
InfoDTO
using microTube::video::VideoIndexer::InfoDTO = microTube::dto::InfoJsonDTO
Definition at line 39 of file VideoIndexer.hpp.
UUIDList
using microTube::video::VideoIndexer::UUIDList = oatpp::List<oatpp::String>
Definition at line 40 of file VideoIndexer.hpp.
VideoInfo
using microTube::video::VideoIndexer::VideoInfo = oatpp::Object<InfoDTO>
Definition at line 41 of file VideoIndexer.hpp.
VideoInfoList
using microTube::video::VideoIndexer::VideoInfoList = std::list<VideoInfo>
Definition at line 43 of file VideoIndexer.hpp.
VideoInfoMap
using microTube::video::VideoIndexer::VideoInfoMap = std::unordered_map<std::string, VideoInfo>
Definition at line 42 of file VideoIndexer.hpp.
Member Enumeration Documentation
SortStyle
enum microTube::video::VideoIndexer::SortStyle
Enumerator
SortStyleASC
SortStyleDESC
Definition at line 129 of file VideoIndexer.hpp.
UUIDSort
enum microTube::video::VideoIndexer::UUIDSort
Enumerator
UUIDSortDate
UUIDSortLikes
UUIDSortDislikes
UUIDSortUniqueViews
Definition at line 121 of file VideoIndexer.hpp.
Constructor & Destructor Documentation
VideoIndexer()
microTube::video::VideoIndexer::VideoIndexer (const std::string & BasePath) inline
Definition at line 45 of file VideoIndexer.hpp.
References IndexingThread(), and m_worker.
~VideoIndexer()
microTube::video::VideoIndexer::~VideoIndexer () inline
Definition at line 50 of file VideoIndexer.hpp.
References m_cv, m_end, and m_worker.
Member Function Documentation
getCategoryList()
UUIDList microTube::video::VideoIndexer::getCategoryList (const oatpp::String & category) inline
Definition at line 265 of file VideoIndexer.hpp.
References m_videos.
getChannelList()
UUIDList microTube::video::VideoIndexer::getChannelList (const oatpp::UInt64 channelId) inline
Definition at line 254 of file VideoIndexer.hpp.
References m_videos.
getDisikeCountFor()
oatpp::UInt64 microTube::video::VideoIndexer::getDisikeCountFor (const std::string & uuid) inline
Definition at line 219 of file VideoIndexer.hpp.
getFullList()
UUIDList microTube::video::VideoIndexer::getFullList () inline
Definition at line 243 of file VideoIndexer.hpp.
References m_videos.
getInfosFor()
VideoInfoList microTube::video::VideoIndexer::getInfosFor (const UUIDList & list) inline
Definition at line 280 of file VideoIndexer.hpp.
References m_videos.
getLikeCountFor()
oatpp::UInt64 microTube::video::VideoIndexer::getLikeCountFor (const std::string & uuid) inline
Definition at line 207 of file VideoIndexer.hpp.
getUniqueViewCountFor()
oatpp::UInt64 microTube::video::VideoIndexer::getUniqueViewCountFor (const std::string & uuid) inline
Definition at line 231 of file VideoIndexer.hpp.
getVideoMap()
std::pair< VideoInfoMap, uintmax_t > microTube::video::VideoIndexer::getVideoMap () inline
Definition at line 93 of file VideoIndexer.hpp.
References m_BasePath.
IndexingThread()
static void microTube::video::VideoIndexer::IndexingThread (VideoIndexer *const instance) inline static
Definition at line 57 of file VideoIndexer.hpp.
References getVideoMap(), m_BasePath, m_cv, m_end, m_videos, mtx, and videos.
lookupInfo()
VideoInfo microTube::video::VideoIndexer::lookupInfo (const std::string & uuid) inline
Definition at line 311 of file VideoIndexer.hpp.
References m_videos.
lookupInfoManual() [1/2]
VideoInfo microTube::video::VideoIndexer::lookupInfoManual (const std::string & uuid) inline
Definition at line 292 of file VideoIndexer.hpp.
References lookupInfoManual(), and m_BasePath.
lookupInfoManual() [2/2]
static VideoInfo microTube::video::VideoIndexer::lookupInfoManual (const std::string & uuid, const std::string & VideoDirectory) inline static
Definition at line 297 of file VideoIndexer.hpp.
References OATPP_COMPONENT().
OATPP_COMPONENT() [1/2]
microTube::video::VideoIndexer::OATPP_COMPONENT (std::shared_ptr< microTube::component::DatabaseClient > , m_database) private
OATPP_COMPONENT() [2/2]
microTube::video::VideoIndexer::OATPP_COMPONENT (std::shared_ptr< oatpp::data::mapping::ObjectMapper > , m_ObjectMapper) private
searchFor()
UUIDList microTube::video::VideoIndexer::searchFor (const std::string & str, const size_t amount = 15) inline
Definition at line 339 of file VideoIndexer.hpp.
References m_videos.
sortBy()
void microTube::video::VideoIndexer::sortBy (const UUIDSort sortCategory, UUIDList & list, const SortStyle sortStyle = SortStyleASC) inline
Definition at line 135 of file VideoIndexer.hpp.
References SortDate(), SortDislikes(), SortLikes(), SortUniqueViews(), UUIDSortDate, UUIDSortDislikes, UUIDSortLikes, and UUIDSortUniqueViews.
SortDate()
void microTube::video::VideoIndexer::SortDate (UUIDList & list, const SortStyle sortStyle) inline private
Definition at line 148 of file VideoIndexer.hpp.
References m_videos, SortStyleASC, and SortStyleDESC.
SortDislikes()
void microTube::video::VideoIndexer::SortDislikes (UUIDList & list, const SortStyle sortStyle) inline private
Definition at line 176 of file VideoIndexer.hpp.
References getDisikeCountFor(), m_videos, SortStyleASC, and SortStyleDESC.
SortLikes()
void microTube::video::VideoIndexer::SortLikes (UUIDList & list, const SortStyle sortStyle) inline private
Definition at line 162 of file VideoIndexer.hpp.
References getLikeCountFor(), m_videos, SortStyleASC, and SortStyleDESC.
SortUniqueViews()
void microTube::video::VideoIndexer::SortUniqueViews (UUIDList & list, const SortStyle sortStyle) inline private
Definition at line 190 of file VideoIndexer.hpp.
References getUniqueViewCountFor(), m_videos, SortStyleASC, and SortStyleDESC.
updateVideoInfo()
bool microTube::video::VideoIndexer::updateVideoInfo (const oatpp::Object< InfoDTO > & dto, const bool isNew = false) inline
Definition at line 319 of file VideoIndexer.hpp.
References m_BasePath, and m_videos.
Member Data Documentation
m_BasePath
std::string microTube::video::VideoIndexer::m_BasePath private
Definition at line 449 of file VideoIndexer.hpp.
m_cv
std::condition_variable microTube::video::VideoIndexer::m_cv private
Definition at line 459 of file VideoIndexer.hpp.
m_end
std::atomic<bool> microTube::video::VideoIndexer::m_end private
Definition at line 458 of file VideoIndexer.hpp.
[struct]
struct { ... } microTube::video::VideoIndexer::m_videos
m_worker
std::thread microTube::video::VideoIndexer::m_worker private
Definition at line 450 of file VideoIndexer.hpp.
mtx
std::mutex microTube::video::VideoIndexer::mtx
Definition at line 455 of file VideoIndexer.hpp.
videos
VideoInfoMap microTube::video::VideoIndexer::videos
Definition at line 456 of file VideoIndexer.hpp.
The documentation for this class was generated from the following file:
VideoIndexer.hpp